### ISSUE TITLE
The usual #114488 background isn't used, dark blue background used by default 

### ISSUE THREAD

**Issue by brihadeesh** [KimNorgaard/vim-frign#1]
Hi, I just tried this out since I've been trying to create a very similar colour scheme for my terminals. This, however, gives me a darker blue background. In the screenshot below, you can see the contrast between the blue of the neovim background and the rest of the terminal and status bar. Any suggestions on what I can do to change the background to the usual #114488?
![frign2016_1](https://user-images.githubusercontent.com/32803930/61316003-9d6a0600-a81d-11e9-8a8c-700242e63448.png)

**Comment by KimNorgaard** [comment]
Is your vim setup to use 24-bit color? Otherwise, as stated in the README it will look bad.

**Comment by KimNorgaard** [comment]
This is what I do:
```vim
set termguicolors
set t_8f=^[[38;2;%lu;%lu;%lum       " 24 bit colors
set t_8b=^[[48;2;%lu;%lu;%lum
```
The `^[^ is the escape character.

**Comment by brihadeesh** [comment]
Oh don't know how I missed that. I'm using 256 colours. Will change it appropriately. Thanks!

Closing this now.
